language: node_js
node_js: 6.11.0
cache: yarn
sudo: required
services:
  - docker
install:
  - npm install -g gatsby-cli
script:
  - docker run -v $(pwd):/app asifrc/gatsbyjs-dev:latest gatsby build
  - ls -la
